<?php
// This file generated by Propel 1.7.2-dev convert-conf target
// from XML runtime conf file D:\Programowanie\Eclipse\sielanka_rusinowo\project\dev\current\module\Propel\runtime-conf.xml
$conf = array (
  'datasources' => 
  array (
    'sielanka_rusinowo' => 
    array (
      'adapter' => 'mysql',
      'connection' => 
      array (
        'dsn' => 'mysql:host=localhost;dbname=domki',
        'user' => 'root',
        'password' => 'admin',
      ),
    ),
    'default' => 'sielanka_rusinowo',
  ),
  'log' => 
  array (
    'type' => 'file',
    'name' => './propel.log',
    'ident' => 'sielanka_rusinowo',
    'level' => '7',
  ),
  'generator_version' => '1.7.2-dev',
);
$conf['classmap'] = include(dirname(__FILE__) . DIRECTORY_SEPARATOR . 'classmap-sielanka_rusinowo-conf.php');
return $conf;